camera_matrix:
- - 530.1266206715039
  - 0.0
  - 356.22013016411313
- - 0.0
  - 531.2239358847315
  - 315.1643567790345
- - 0.0
  - 0.0
  - 1.0
distortion_coefficients:
- - -0.501075610928276
  - 0.29587190291575793
  - 0.0019673861997249542
  - 0.00041782023136265154
  - -0.09225676373929691
image_height: 480
image_width: 640
mean_reprojection_error: 0.03913123553711681
new_camera_matrix:
- - 284.5960693359375
  - 0.0
  - 311.8866438820405
- - 0.0
  - 274.7319030761719
  - 352.7575755747239
- - 0.0
  - 0.0
  - 1.0
roi:
  height: 253
  width: 373
  x: 121
  y: 190
